version: 2

defaults: &defaults 
  working_directory: ~/root
  docker:
    - image: circleci/node:8.10

jobs:

  build:
    <<: *defaults
    steps:
      - run:
          name: Install Code Climate test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

  main-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/root/tmp
      - run:
          name: Install main dependencies
          command: npm install
      - run:
          name: Run core tests
          command: | 
            npm run coverage 
            ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/codeclimate.core.json
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.core.json

  submit-coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/root/tmp
      - run:
          name: Upload combined coverage to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 1 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json

workflows:
  version: 2

  all:
    jobs:
      - build
      - main-tests:
          requires:
            - build
      - submit-coverage:
          requires:
            - main-tests